sudo: required
services: 
  - docker 

before_install
  - docker build -t apkwan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true apkwan/docker-react npm run test

language: generic 